name: Scrape Duolingo Profile

on:
  schedule:
    - cron: "0 7-23,0 * * *"  # Runs at 07:00, 08:00, ..., 23:00, 00:00
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install --with-deps  # Installs browsers too

      - name: Run Scraper
        run: python scraper.py
